<?php
    $recaptcha = $this->config->admin->login->recaptcha;
    $gauth = $this->config->admin->login->googleauthenticator;
    $captcha = $this->config->admin->login->captcha;
?>
<div class="page-login">
    <div class="card">
        <form class="card-body needs-validation main" method="POST" novalidate>
            <h5 class="card-title">Login</h5>

            <?php if($error): ?>
            <div class="alert alert-danger alert-dismissible fade show">
                <strong>Whoops!</strong> The credentials is invalid
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <?php endif; ?>

            <?= $form->field('name'); ?>
            <?php if($recovery): ?>
                <div class="text-right">
                    <small><a href="<?= hs($recovery) ?>">Forget password?</a></small>
                </div>
            <?php endif; ?>

            <?= $form->field('password'); ?>

            <?php if($gauth): ?>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Google Authenticator" name="gatoken" required>
                </div>
            <?php endif; ?>

            <?php if($captcha): ?>
                <?php
                    $captcha_image = \LibCaptcha\Library\Captcha::image($form->csrfToken(), 'admin');
                ?>
                <img src="<?= $captcha_image ?>" class="captcha-image">
                <div class="form-group">
                    <?php if($captcha_error): ?>
                        <input type="text" class="form-control is-invalid" placeholder="Captcha Answer" name="captcha"
                        required>
                        <div class="invalid-feedback">Wrong captcha answer</div>
                    <?php else: ?>
                        <input type="text" class="form-control" placeholder="Captcha Answer" name="captcha"
                        required>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <?= $form->csrfField('noob'); ?>

            <?php if ($recaptcha): ?>
                <input type="hidden" id="recaptcha" name="recaptcha">
            <?php endif; ?>

            <div>
                <button class="btn btn-primary btn-block">Login</button>
            </div>
            
            <?php if($register): ?>
                <div class="pt-3 text-center">
                    Don't have an account? <a href="<?= hs($register) ?>">Create one</a>.
                </div>
            <?php endif; ?>
        </form>
    </div>
</div>

<?php if ($recaptcha): ?>
<?php $sitekey = $this->config->libRecaptcha->sitekey; ?>
<script src="https://www.google.com/recaptcha/api.js?render=<?= $sitekey ?>"></script>
<script>
    grecaptcha.ready(() => {
        let opts = {action:'login'}
        grecaptcha.execute('<?= $sitekey ?>', opts)
            .then(token => {
                document.querySelector('#recaptcha').value = token
            })
    })
</script>
<?php endif; ?>
<?php if($captcha): ?>
    <style>.captcha-image{ display:block;margin:0 auto 10px; }</style>
<?php endif; ?>
