<div class="page-login">
    <div class="card">
        <form class="card-body needs-validation main" method="POST" novalidate>
            <h5 class="card-title">Login</h5>

            <?php if($error): ?>
            <div class="alert alert-danger alert-dismissible fade show">
                <strong>Whoops!</strong> The credentials is invalid
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <?php endif; ?>

            <?= $form->field('name'); ?>
            <?= $form->field('password'); ?>
            <?= $form->csrfField('noob'); ?>

            <div>
                <button class="btn btn-primary btn-block">Login</button>
            </div>

            <?php if($recovery || $register): ?>
                <div class="row pt-3">
                    <div class="col-6">
                        <?php if($recovery): ?>
                            <a href="<?= hs($recovery) ?>">Recovery</a>
                        <?php endif; ?>
                    </div>
                    <div class="col-6 text-right">
                        <?php if($register): ?>
                            <a href="<?= hs($register) ?>">Register</a>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
        </form>
    </div>
</div>