<div class="page-login">
    <div class="card">
        <form class="card-body needs-validation main" method="POST" novalidate>
            <h5 class="card-title">Login</h5>

            <?php if($error): ?>
            <div class="alert alert-danger alert-dismissible fade show">
                <strong>Whoops!</strong> The credentials is invalid
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <?php endif; ?>

            <?= $form->field('name'); ?>
            <?= $form->field('password'); ?>
            <?= $form->csrfField('noob'); ?>

            <div>
                <button class="btn btn-primary btn-block">Login</button>
            </div>
        </form>
    </div>
</div>